# Generated by Django 3.2.11 on 2022-01-11 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scooter',
            name='provider_id',
        ),
        migrations.AddField(
            model_name='scooter',
            name='latitude',
            field=models.FloatField(default=None, verbose_name='latitude'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scooter',
            name='longitude',
            field=models.FloatField(default=None, verbose_name='longitude'),
            preserve_default=False,
        ),
    ]
