# Generated by Django 3.2.11 on 2022-01-11 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0002_auto_20220111_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='scooter',
            name='provider',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scooters.provider'),
            preserve_default=False,
        ),
    ]
