# Generated by Django 3.2.11 on 2022-01-11 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0004_auto_20220111_1454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Provider',
            new_name='Providers',
        ),
        migrations.RenameModel(
            old_name='Scooter',
            new_name='Scooters',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
