# Generated by Django 3.2.11 on 2022-01-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0005_auto_20220111_1634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Providers',
            new_name='Provider',
        ),
        migrations.RenameModel(
            old_name='Scooters',
            new_name='Scooter',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
