# Generated by Django 3.2.11 on 2022-01-11 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0006_auto_20220111_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scooter',
            name='is_free',
        ),
        migrations.AddField(
            model_name='scooter',
            name='used_by_user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='scooters.user'),
        ),
    ]
