# Generated by Django 3.2.11 on 2022-01-11 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0008_alter_scooter_used_by_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scooter',
            name='used_by_user',
        ),
    ]
