# Generated by Django 3.2.11 on 2022-01-12 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0013_alter_scooter_used_by_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooters.scooter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooters.user')),
            ],
        ),
    ]
