# Generated by Django 3.2.11 on 2022-01-14 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0014_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('start_ride_time', models.DateTimeField(auto_now_add=True)),
                ('end_ride_time', models.DateTimeField(blank=True)),
                ('scooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooters.scooter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scooters.user')),
            ],
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.AddField(
            model_name='scooter',
            name='last_ride',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scooter_ride', to='scooters.ride'),
        ),
    ]
