# Generated by Django 3.2.11 on 2022-01-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scooters', '0016_alter_ride_end_ride_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='start_ride_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
